### ISSUE TITLE
jamonapi benchmark test slow for proxy mode

### ISSUE THREAD

**Issue by bwzhang2011** [stevensouza/jamonapi#11]
@stevensouza, when test with jmh, I found there's performance gap between direct calling and monitor proxy calling while executing jmh test. I knew that there's a simple test like TestClassPerformance to show the basic execution result under loop test, but it's different running under in jmh. here comes my test cases like follows:
import java.util.concurrent.TimeUnit;

import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Measurement;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OperationsPerInvocation;
import org.openjdk.jmh.annotations.OutputTimeUnit;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.Setup;
import org.openjdk.jmh.annotations.State;
import org.openjdk.jmh.annotations.Warmup;

import com.jamonapi.FIFOBufferEnable;
import com.jamonapi.MonitorFactory;
import com.jamonapi.proxy.MonProxyFactory;

@State(Scope.Thread)
@Measurement(iterations = 5, time = 5)
@Warmup(iterations = 5)
@Fork(3)
@BenchmarkMode(Mode.ALL)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
public class TestMonitorProxyInLoop {

```
private IHelloWorld helloworld;

private IHelloWorld helloworldProxy;

@Setup
public void setup() throws Exception {
    helloworld = new HelloWorldImpl();

    helloworldProxy = (IHelloWorld) (MonProxyFactory.monitor(helloworld,IHelloWorld.class));
}

private String getDirectResponse(int count) {
    String response = null;

    for (int i = 0; i < count; i++) {
        response = helloworld.getResponse(String.valueOf(i));
    }

    return response;
}

private String getProxyResponse(int count) {
    String response = null;

    for (int i = 0; i < count; i++) {
        response = helloworldProxy.getResponse(String.valueOf(i));
    }

    return response;
}

private String getProxyDisableResponse(int count) {
    MonitorFactory.setEnabled(false);

    String response = null;

    for (int i = 0; i < count; i++) {
        response = helloworldProxy.getResponse(String.valueOf(i));
    }

    MonitorFactory.setEnabled(true);

    return response;
}

@Benchmark
@OperationsPerInvocation(1000)
public String testDirectResponse_1000() {
    return getDirectResponse(1000);
}

@Benchmark
@OperationsPerInvocation(1000)
public String testProxyResponse_1000() {
    return getProxyResponse(1000);
}

@Benchmark
@OperationsPerInvocation(1000)
public String testProxyDisableResponse_1000() {
    return getProxyDisableResponse(1000);
}
```

}

from the benchmark, there're huge gap between direct calling and proxy calling especially monitor brought in.  I hope you had your spare time, just share some benchmark test with us to improve jamonapi performance. if there are mistakes, please help me point it out where I was wrong.

**Comment by bwzhang2011** [comment]
public interface IHelloWorld {

```
 String getResponse(String hello);
```

}

import java.util.Date;

public class HelloWorldImpl implements IHelloWorld {

```
@Override
public String getResponse(String hello) {
```

//      try {
//          Thread.sleep(1L);
//      } catch (InterruptedException e) {
//  
//      }
        return "say hello:" + hello + ",at:" + new Date();
    }

}

**Comment by stevensouza** [comment]
Ok, thanks I will look into it and get back to you.

Steve

**Comment by bwzhang2011** [comment]
@stevensouza, thanks for review and hope more jmh tests could be provide if available.

**Comment by stevensouza** [comment]
With any monitoring you should think and plan what is best to monitor and not monitor every method.  For example the method that you are monitoring simply returns data and so is not a good candidate for monitoring. The best candidates for monitoring are methods that perform IO of some sort or are critical in nature in some other way (for example it is important to see if they close resources). 

I would expect proxies and jamon to add overhead if you are simply returning a string from a method which is very fast.  Proxies probably call many methods to perform their action. Jamon has to track min, max, activity, most recent call, call its own methods and more.  Proxy overhead is related to jdk limitations and not really related to jamon. In general all the useful information jamon creates doesn't come for free.  However, by helping you to detect your performance bottlenecks you should be able to make other parts of your code faster if needed and so more than offset any additional overhead that proxies/jamon may create. In addition Jamon let's you look at any thrown stack traces and count any exceptions that are thrown which is very useful for troubleshooting.

I performed some of my own tests and proxies themselves add more overhead than jamon.  If you are measuring IO such as jdbc calls, web hits this overhead is insignificant.  Also, keep in mind you can disable jamon and proxies at runtime and their overhead drops to near 0.  

A couple comments about your performance tests.  
- I wouldn't expect a performance test of 1000 calls to be long enough for the optimizer to properly optimize
- MonitorFactory.setEnabled(false) - This alone doesn't disable proxies.  It only disables jamon monitoring, but the proxy itself is still called.  To bypass the proxy entirely you would need to call:         MonProxyFactory.enableAll(false).  This should bring the performance of 'getProxyDisableResponse' very close to 'getDirectResponse'

Also the overhead due to the inherent nature of proxies can be reduced by using Automon or AspectJ. But I wouldn't worry about that unless the overhead becomes a true application bottleneck and not just a theoretical one. Other things that can be done if needed are to not monitor every call, but to monitor every random Nth call (say monitor every 1 in a 100 call).

Steve

**Comment by bwzhang2011** [comment]
@stevensouza, thanks a lot for your comments and advice. as for your suggestion, we should monitor every random Nth call as sample frequency to reduce the impact of monitor and the sample frequency could be adjusted towards different resources.

**Comment by bwzhang2011** [comment]
@stevensouza, https://github.com/openzipkin/brave/blob/0a4a5d209dcae9b2dc1b7e62d95517b04da4deaf/brave-core/src/main/java/com/github/kristofa/brave/FixedSampleRateTraceFilter.java   as such suggestion I would decide to add some support for sample rate control in monitor next week and make such control.

**Comment by stevensouza** [comment]
One issue to think about is do you want it to monitor every Nth (say 100th) request or would the measurements be better if you on average measured every Nth.  For example the first case measures exactly every 100th and the second case would on average measure every 100th.  So maybe the first time it would be the 95th, the second time 104th, 99th, 98th, 101st etc.  But over time on average it would be every 100th.  I would prefer the 2nd if i had to pick one.  Of course you could implement both too (FixedNth and RandomNth)

**Comment by bwzhang2011** [comment]
@stevensouza, thanks for your advice. I think FIxedNth seems to be more simple and better performance. I will try it first and make it to be sampled in MonProxyFactory to control whether it should be return the direct object or the proxy object.

**Comment by bwzhang2011** [comment]
@stevensouza, according to the discussion, I decide to close such issue and it's better bring in some samplerate control into jamon control and hope you could provide some official support as defined.
by the way, jamonapi should try to improve the proxy performance or add more chapter to leave us more examples towards it.
